# Generated by Django 4.2.1 on 2023-05-21 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_administrador', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_admin', models.CharField(max_length=50)),
                ('email_admin', models.CharField(max_length=50)),
                ('horarios_admin', models.CharField(max_length=50)),
                ('tel_admin', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Tabla de administrativo',
                'verbose_name_plural': 'Administrativos',
                'db_table': 'administrativo',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('cod_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precio_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion_pedido', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tabla de carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=255)),
                ('tel_cliente', models.BigIntegerField()),
                ('email_cliente', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tabla de clientes',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('cod_postal', models.IntegerField(primary_key=True, serialize=False)),
                ('destinatario', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tabla de destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destino',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('cod_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('descripcion_serv', models.CharField(max_length=400)),
                ('precio_kg_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tabla de servicios',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('postal_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.destino')),
            ],
            options={
                'verbose_name': 'Tabla de sucursales',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_transportista', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_transp', models.CharField(max_length=50)),
                ('email_transp', models.CharField(max_length=50)),
                ('horarios_transp', models.CharField(max_length=50)),
                ('tel_transp', models.BigIntegerField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.sucursal')),
            ],
            options={
                'verbose_name': 'Tabla de transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'transportista',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('patente', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
                ('ano_vehiculo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'tablaVehiculos',
                'verbose_name_plural': 'tabla-de-Vehiculos',
                'db_table': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo_Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.vehiculos')),
                ('transp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.transportista')),
            ],
            options={
                'verbose_name': 'vehiculo-conductor',
                'verbose_name_plural': 'vehiculos-conductores',
                'db_table': 'Vehiculo_Conductor',
            },
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('cod_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_paquete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.carrito')),
                ('servicio_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.servicios')),
            ],
            options={
                'verbose_name': 'Tabla de Paquetes',
                'verbose_name_plural': 'Paquetes',
                'db_table': 'Paquete',
            },
        ),
        migrations.CreateModel(
            name='Paquete_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.paquetes')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.vehiculos')),
            ],
            options={
                'verbose_name': 'paquetevehiculo',
                'verbose_name_plural': 'paquete-vehiculos',
                'db_table': 'Paquete_Vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('cod_factura', models.AutoField(primary_key=True, serialize=False)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.clientes')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.administrativo')),
            ],
            options={
                'verbose_name': 'Tabla de facturas',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='factura_cod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.factura'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='postal_cod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.destino'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFLE.sucursal'),
        ),
    ]
